export const assets = {
  OmnikadoLogo: "/assets/omnikado-logo.svg",
  OmnikadoMan: "/assets/omnikado-man.svg",
  AmazonLogo: "/assets/amazon.svg",
  AmexLogo: "/assets/amex.svg",
  GooglePlayLogo: "/assets/g-play.svg",
  NikeLogo: "/assets/nike.svg",
  NordstromLogo: "/assets/nordstrom.svg",
  SephoraLogo: "/assets/sephora.svg",
  SteamLogo: "/assets/steam.svg",
  VanillaLogo: "/assets/vanilla.svg",
  WalmartLogo: "/assets/walmart.svg",
  WalmartGiftCard: "/assets/gc-walmart.svg",
  SteamGiftCard: "/assets/gc-steam.svg",
  NordstromGiftCard: "/assets/gc-nordstrom.svg",
  NikeGiftCard: "/assets/gc-nike.svg",
  AmazonGiftCard: "/assets/gc-amazon.svg",
  SephoraGiftCard: "/assets/gc-sephora.svg",
  VanillaGiftCard: "/assets/gc-vanilla.svg",
  GooglePlayGiftCard: "/assets/gc-gplay.svg",
  EbayGiftCard: "/assets/gc-ebay.svg",
  Email: "/assets/email.svg",
  ShowPassword: "/assets/show.svg",
  HidePassword: "/assets/hide.svg",
  Google: "/assets/google.svg",
  Success: "/assets/success.svg",
};
